### ISSUE TITLE
createRTCSessionDescription

### ISSUE THREAD

**Issue by colin354** [linkingvision/h5sconsole#3]
src/assets/h5splayer.js: Identifier 'createRTCSessionDescription' has already been declared (1:3716)

![image](https://user-images.githubusercontent.com/20513374/76046854-09130600-5f9c-11ea-8b8d-a21f1919d519.png)

你好，我再使用的时候，遇到了这样的重复定义的问题，请问下您那边是否遇到过呢？

**Comment by xsmart** [comment]
master版本已经解决这个问题，下个版本会提交, 也可以先使用这个 
https://github.com/linkingvision/rapidstorweb/blob/master/src/assets/js/h5splayer.js
